/* list of events */
typedef enum {
  EVENT_START_PROGRAM,
  EVENT_START_GAME,
  EVENT_FIRST_PLAYER_ACTION,
  EVENT_PLAYER_FILLED_IN,
  EVENT_PLAYER_X_NEXT_TURN,
  EVENT_PLAYER_O_NEXT_TURN,
  EVENT_WINNER_ANNOUNCE,
  EVENT_END_GAME,
  EVENT_RESTART,
  EVENT_LAST
}Events;

/* return type for event functions */
typedef enum {
    RET_EVENT_SUCCESS,
    RET_EVENT_FAIL
} EventsRet;