name: CI pipeline

on: [push]

jobs:
  linting:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install clang-format
        run: sudo apt-get install -y clang-format-14

      - name: Check clang-format version
        run: clang-format --version

      - name: Check formatting
        run: |
          NOT_FORMATTED=$(find . -iname *.c -o -iname *.h | xargs clang-format -style=file -output-replacements-xml | grep "<replacement " || true)
          if [ ! -z "$NOT_FORMATTED" ]; then
            echo "Please run following command on your project repository:"
            echo "find . -iname *.c -o -iname *.h | xargs clang-format -i -style=file"
            exit 1
          fi

  compile-and-build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Compile the Code Using Make
      run: make
    - name: Upload Compiled Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-output
        path: |
          bin/run

  test-and-run:
    if: false # This job is disabled for now
    needs: compile-and-build
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Download Compiled Build Artifact
      uses: actions/download-artifact@v2
      with:
        name: build-output
        path: bin
    - name: Set Execute Permission and Run Executable
      run: |
        pwd
        ls -l
        chmod +x bin/run
        mkdir -p logs
        cd bin
        ./run
